### ISSUE TITLE
scotmid spider broken (possibly due to change in scotmid website)

### ISSUE THREAD

**Issue by rjw62** [alltheplaces/alltheplaces#10256]
### Spider name

scotmid

### Log output

https://alltheplaces-data.openaddresses.io/runs/2024-09-07-13-32-11/logs/scotmid.txt

### Backtrace (if applicable)

Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/utils/defer.py", line 279, in iter_errback
    yield next(it)
          ^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/utils/python.py", line 350, in __next__
    return next(self.data)
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/utils/python.py", line 350, in __next__
    return next(self.data)
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/core/spidermw.py", line 106, in process_sync
    for r in iterable:
  File "/home/ubuntu/locations/middlewares/track_sources.py", line 31, in process_spider_output
    for item in result or []:
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/core/spidermw.py", line 106, in process_sync
    for r in iterable:
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/spidermiddlewares/referer.py", line 352, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/core/spidermw.py", line 106, in process_sync
    for r in iterable:
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/spidermiddlewares/urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/core/spidermw.py", line 106, in process_sync
    for r in iterable:
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/spidermiddlewares/depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/core/spidermw.py", line 106, in process_sync
    for r in iterable:
  File "/home/ubuntu/locations/spiders/scotmid.py", line 18, in parse
    for store in response.json():
                 ^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/http/response/text.py", line 85, in json
    self._cached_decoded_json = json.loads(self.body)
                                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Example bad data or results

Spider returns no stores.

### Expected behaviour or results

Spider should return over 250 stores of different types.

### Possible causes?

I think the page structure that was being spidered may have changed. If the previously used JSON is no longer available, then the following my be workable alternative...

There's a sitemap at https://scotmid.coop/wpsl_stores-sitemap.xml that probably lists all the stores, but we'd then need to crawl all the individual pages. I think it may need some custom code to extract the store details. In particular the store type is not obvious from looking at the page, but it does seem to be included in the HTML via

`<main id="content" class="site-main post-24770 wpsl_stores type-wpsl_stores status-publish hentry wpsl_store_category-scotmid">`

The suffix to `wpsl_store_category-` can be one of scotmid, semichem, funeral-branches, or lakes-and-dales for the different types detected by the existing spider.

**Comment by CloCkWeRX** [comment]
https://github.com/alltheplaces/alltheplaces/blob/3fdfca9cd1d865a314293e911dcb65be77c490ec/locations/spiders/bakers_delight.py#L12 is a good example of crawling this kind of sitemap I think.
