### ISSUE TITLE
Invalid json for sunoco.geojson and circle_k.geojson

### ISSUE THREAD

**Issue by thomas536** [alltheplaces/alltheplaces#1517]
Seems like a stray line in the middle of the json that is a single errant comma for the 2020-05-20-14-42-48 run.

```
{"type": "Feature", "id": "3Zts0iWlMJkO1RQe3dRTm8Cyook=", "properties": {"ref": "3242591", "amenity:fuel": true, "atm": false, "car_wash": false, "fuel:diesel": false, "fuel:kerosene": false, "@spider": "sunoco", "addr:full": "208 E. MAIN STREET", "addr:city": "FOREST CITY", "addr:state": "NC", "addr:postcode": 28043, "addr:country": "US", "name": "Sunoco #3242591", "phone": 8282451252, "opening_hours": "24/7", "brand": "Sunoco", "brand:wikidata": "Q1423218"}, "geometry": {"type": "Point", "coordinates": [-81.861442, 35.332902]}},
, 
{"type": "Feature", "id": "vf-tYg2drj3sycr8fJIXBL_hGxE=", "properties": {"ref": "3547098", "amenity:fuel": true, "atm": false, "car_wash": false, "fuel:diesel": false, "fuel:kerosene": false, "@spider": "sunoco", "addr:full": "114 LOUDON RD", "addr:city": "CONCORD", "addr:state": "NH", "addr:postcode": 3301, "addr:country": "US", "name": "Sunoco #3547098", "phone": 6032891534, "opening_hours": "24/7", "brand": "Sunoco", "brand:wikidata": "Q1423218"}, "geometry": {"type": "Point", "coordinates": [-71.512709, 43.213559]}},
```

```
{"type": "Feature", "id": "4wDgwLnmljLMjtE4B_QS02_LqYo=", "properties": {"ref": "2022", "amenity:fuel": true, "fuel:diesel": null, "car_wash": null, "shop": "convenience", "@spider": "circle_k", "addr:full": "312 Amirault Street", "addr:city": "Dieppe", "addr:state": "NB", "addr:postcode": "E1A 1G2", "addr:country": "Canada", "name": "Circle K", "website": "/store-locator/Canada/dieppe/312-amirault-street/2022", "brand": "Circle K", "brand:wikidata": "Q3268010"}, "geometry": {"type": "Point", "coordinates": [-64.6616818, 46.0458664]}},
, 
{"type": "Feature", "id": "D0EZgW1vLh4KGI13aNAPxLtpCsU=", "properties": {"ref": "2536", "amenity:fuel": true, "fuel:diesel": null, "car_wash": null, "shop": "convenience", "@spider": "circle_k", "addr:full": "157 CHAMPLAIN ST.", "addr:city": "Dieppe", "addr:state": "NB", "addr:postcode": "E1A 1N5", "addr:country": "Canada", "name": "Circle K", "website": "/store-locator/Canada/dieppe/157-champlain-st/2536", "brand": "Circle K", "brand:wikidata": "Q3268010"}, "geometry": {"type": "Point", "coordinates": [-64.75147, 46.09518]}},
```

**Comment by iandees** [comment]
Ah yea, this is a bug in the way the output works. The `,` represents a feature that was filtered out for some reason.

**Comment by iandees** [comment]
The custom [`GeoJSONItemExporter`](https://github.com/alltheplaces/alltheplaces/blob/master/locations/exporters.py#L75) extends the built-in scrapy [`JSONItemExporter`](https://github.com/scrapy/scrapy/blob/master/scrapy/exporters.py#L96). I think that code writes out a newline + comma before the dedupe pipeline step detects that it shouldn't write it.

**Comment by thomas536** [comment]
yeah from looking at that code there shouldn't have been any way that it could have json encoded a dict to product an empty string. Finally running the spider, the encoder fails, so it makes sense that it never finishes persisting that item.

```
2020-05-29 10:04:03 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x7f3f4b685130>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/usr/lib/python3/dist-packages/scrapy/extensions/feedexport.py", line 266, in item_scraped
    slot.exporter.export_item(item)
  File "/usr/lib/python3/dist-packages/scrapy/exporters.py", line 129, in export_item
    itemdict = dict(self._get_serialized_fields(item))
  File "/home/tgarner/projects/third_party/github.com/thomas536/alltheplaces/locations/exporters.py", line 88, in _get_serialized_fields
    float(item['lat'])
ValueError: could not convert string to float: '46.724998Â\xa0'
```

**Comment by iandees** [comment]
I think this is fixed with the latest PRs up there. Reopen if you run into it again.
