### ISSUE TITLE
No new data on alltheplaces.xyz since 17-Apr-2023

### ISSUE THREAD

**Issue by rjw62** [alltheplaces/alltheplaces#5261]
Looking at https://www.alltheplaces.xyz/ and https://www.alltheplaces.xyz/spiders.html the last weekly update seems to have been from 15th April 2023, uploaded on 17th. So the generation has failed for three weeks in a row now.

**Comment by iandees** [comment]
Thanks for asking! I'll take a look after work tonight.

**Comment by iandees** [comment]
The error on the weekly is:

```
Traceback (most recent call last):
---
File "/home/ubuntu/.pyenv/versions/3.10.11/bin/scrapy", line 8, in <module>
sys.exit(execute())
File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/scrapy/cmdline.py", line 125, in execute
settings = get_project_settings()
File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/scrapy/utils/project.py", line 71, in get_project_settings
settings.setmodule(settings_module_path, priority="project")
File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/scrapy/settings/__init__.py", line 316, in setmodule
module = import_module(module)
File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/home/ubuntu/locations/__init__.py", line 3, in <module>
import requests_cache
File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/requests_cache/__init__.py", line 7, in <module>
from .backends import *
File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/requests_cache/backends/__init__.py", line 7, in <module>
from .base import BaseCache, BaseStorage, DictStorage
File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/requests_cache/backends/base.py", line 22, in <module>
from ..serializers import SerializerType, init_serializer
File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/requests_cache/serializers/__init__.py", line 24, in <module>
from .cattrs import CattrStage
File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/requests_cache/serializers/cattrs.py", line 19, in <module>
from cattr import Converter
File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/cattr/__init__.py", line 1, in <module>
from .converters import BaseConverter, Converter, GenConverter, UnstructureStrategy
File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/cattr/converters.py", line 1, in <module>
from cattrs.converters import (
File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/cattrs/__init__.py", line 1, in <module>
from .converters import BaseConverter, Converter, GenConverter, UnstructureStrategy
File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/cattrs/converters.py", line 24, in <module>
from cattrs.errors import IterableValidationError, StructureHandlerNotFoundError
File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/cattrs/errors.py", line 3, in <module>
from cattrs._compat import ExceptionGroup
File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/cattrs/_compat.py", line 43, in <module>
from exceptiongroup import ExceptionGroup
ModuleNotFoundError: No module named 'exceptiongroup'
```

**Comment by iandees** [comment]
It seems that #5268 lets it run. Not sure why, because `scrapy list` was working for me everywhere (even from the docker image running on my laptop) without that setting.

I'll close this when I see that there's new data from this run.

**Comment by iandees** [comment]
Looks like the data updated, so I'm going to close this out. Thanks for flagging!

**Comment by davidhicks** [comment]
@iandees Looks like it's broken again?

**Comment by iandees** [comment]
Yea, looks like it's running into the same problem as before. The only thing I can think of is that it's using an old Docker image for some reason.

**Comment by Cj-Malone** [comment]
I think one of our dependencies isn't declaring exceptiongroup, try adding it to our dependencies for now

**Comment by iandees** [comment]
exceptiongroup is installed in the image.

**Comment by davidhicks** [comment]
Looks good now with a successful run on 31 May so closing again :)
