### ISSUE TITLE
pipenv install is not sufficient

### ISSUE THREAD

**Issue by rkiddy** [alltheplaces/alltheplaces#7312]
I followed the directions. I am on a Ubuntu 22.04.3 LTS system. I ran:
```
$ git clone git@github.com:alltheplaces/alltheplaces.git
$ (installed pipenv)
$ cd alltheplaces
$ pipenv install
$pipenv run scrapy
```
And I got an error.
```
$ pipenv run scrapy
Traceback (most recent call last):
  File "/home/ray/.local/share/virtualenvs/alltheplaces-3iXQ9kuR/bin/scrapy", line 8, in <module>
    sys.exit(execute())
  File "/home/ray/.local/share/virtualenvs/alltheplaces-3iXQ9kuR/lib/python3.10/site-packages/scrapy/cmdline.py", line 128, in execute
    settings = get_project_settings()
  File "/home/ray/.local/share/virtualenvs/alltheplaces-3iXQ9kuR/lib/python3.10/site-packages/scrapy/utils/project.py", line 71, in get_project_settings
    settings.setmodule(settings_module_path, priority="project")
  File "/home/ray/.local/share/virtualenvs/alltheplaces-3iXQ9kuR/lib/python3.10/site-packages/scrapy/settings/__init__.py", line 385, in setmodule
    module = import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ray/Projects/alltheplaces/locations/__init__.py", line 5, in <module>
    import requests_cache
  File "/home/ray/.local/share/virtualenvs/alltheplaces-3iXQ9kuR/lib/python3.10/site-packages/requests_cache/__init__.py", line 7, in <module>
    from .backends import *
  File "/home/ray/.local/share/virtualenvs/alltheplaces-3iXQ9kuR/lib/python3.10/site-packages/requests_cache/backends/__init__.py", line 7, in <module>
    from .base import BaseCache, BaseStorage, DictStorage
  File "/home/ray/.local/share/virtualenvs/alltheplaces-3iXQ9kuR/lib/python3.10/site-packages/requests_cache/backends/base.py", line 22, in <module>
    from ..serializers import SerializerType, init_serializer
  File "/home/ray/.local/share/virtualenvs/alltheplaces-3iXQ9kuR/lib/python3.10/site-packages/requests_cache/serializers/__init__.py", line 24, in <module>
    from .cattrs import CattrStage
  File "/home/ray/.local/share/virtualenvs/alltheplaces-3iXQ9kuR/lib/python3.10/site-packages/requests_cache/serializers/cattrs.py", line 19, in <module>
    from cattr import Converter
  File "/home/ray/.local/share/virtualenvs/alltheplaces-3iXQ9kuR/lib/python3.10/site-packages/cattr/__init__.py", line 1, in <module>
    from .converters import BaseConverter, Converter, GenConverter, UnstructureStrategy
  File "/home/ray/.local/share/virtualenvs/alltheplaces-3iXQ9kuR/lib/python3.10/site-packages/cattr/converters.py", line 1, in <module>
    from cattrs.converters import (
  File "/home/ray/.local/share/virtualenvs/alltheplaces-3iXQ9kuR/lib/python3.10/site-packages/cattrs/__init__.py", line 1, in <module>
    from .converters import BaseConverter, Converter, GenConverter, UnstructureStrategy
  File "/home/ray/.local/share/virtualenvs/alltheplaces-3iXQ9kuR/lib/python3.10/site-packages/cattrs/converters.py", line 25, in <module>
    from ._compat import (
  File "/home/ray/.local/share/virtualenvs/alltheplaces-3iXQ9kuR/lib/python3.10/site-packages/cattrs/_compat.py", line 40, in <module>
    from exceptiongroup import ExceptionGroup
ModuleNotFoundError: No module named 'exceptiongroup'
```
I do not really know pipenv, but I can see in the Pipfile that the exceptiongroup module is in the dev ... group?

Anyway, I ran
```
$ pipenv install --dev
```

After that, running "pipenv run scrapy" worked. So that should probably be added to the README. Unless something about my configuration is different?

**Comment by iandees** [comment]
Can you check to see what version of Python you're using? The Pipfile was generated with and the CI + weekly runs use 3.11.

**Comment by Cj-Malone** [comment]
exceptiongroup shouldn't be in dev, will it shouldn't be anywhere, but until it's fixed, it should be in the main dependencies Rel: https://github.com/alltheplaces/alltheplaces/issues/5261#issue-1705999758

The docs are probably for development, they should be updated --dev.

**Comment by rkiddy** [comment]
```
$ python3 --version
Python 3.10.12
$ 
```

**Comment by iandees** [comment]
Please update to use Python 3.11 and try again.

**Comment by rkiddy** [comment]
I can, of course, upgrade my python version.  But this is not always doable. I have upgraded python on an ubuntu system and seriously horked myself. This was, mind you, a major upgrade, not something like 3.10 to 3.11. So, your suggestion is valid. But I just wanted to put this out there. :--)

**Comment by iandees** [comment]
I understand that it's difficult to deal with Python versioning, especially when installing via Ubuntu packaging.

My recommendation would be to use [`pyenv`](https://github.com/pyenv/pyenv#installation) and ask `pipenv` to use 3.11 when installing.

I will adjust the Readme to use pyenv and test it on Ubuntu 22.04, put up a PR, and you can see if the suggested documentation change works for you.

**Comment by iandees** [comment]
Can you try the ubuntu instructions over here? https://github.com/alltheplaces/alltheplaces/blob/update-readme/README.md#ubuntu

**Comment by rkiddy** [comment]
Followed the instructions, did the thing, and I think it all worked.

Actually, I do not know how to remove the effect of having run 'pipenv install --dev', so I think that I cannot say this is a whole clean install.

But I did not have pyenv and I installed it and it worked great and the 3.11 python was activated and running 'pipenv run scrapy' gave me a good result.

I think that (AFAIK) it is good.
