### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#8693]
```
2024-06-22 22:27:27 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.firstnational.com.au/pages/real-estate/offices> (referer: None)
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/utils/defer.py", line 279, in iter_errback
    yield next(it)
          ^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/utils/python.py", line 350, in __next__
    return next(self.data)
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/utils/python.py", line 350, in __next__
    return next(self.data)
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/core/spidermw.py", line 106, in process_sync
    for r in iterable:
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/spidermiddlewares/referer.py", line 352, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/core/spidermw.py", line 106, in process_sync
    for r in iterable:
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/spidermiddlewares/urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/core/spidermw.py", line 106, in process_sync
    for r in iterable:
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/spidermiddlewares/depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/core/spidermw.py", line 106, in process_sync
    for r in iterable:
  File "/home/ubuntu/locations/spiders/first_national_real_estate_au.py", line 25, in parse
    .replace("&pg=2", "&pg={}")
     ^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
```

https://alltheplaces-data.openaddresses.io/runs/2024-06-22-13-32-09/logs/first_national_real_estate_au.txt

**Comment by iandees** [comment]
It's helpful to have these, but it's even more helpful to include fixes 😄

**Comment by iandees** [comment]
Looks like the website template for this site is completely different from what the spider is expecting and needs to get updated.

**Comment by matkoniecz** [comment]
> It's helpful to have these, but it's even more helpful to include fixes 😄

OK, I will try then to continue my plan of submitting limited number of issues (few of each type) and PRs where I can (https://codeberg.org/matkoniecz/list_how_openstreetmap_can_be_improved_with_alltheplaces_data/commit/66126233029ed07530b4fc80e6ee0bb207cd3f03 - I have currently this reports disabled by default and I flip them on when already reported things get fixed and I have time to try researching what is going on).

It would be nice to fix that backlog of failing spiders, this is likely easier than writing new ones.

**Comment by CloCkWeRX** [comment]
https://www.firstnational.com.au/scripts/template/58583?pattern=offices&path_info=/pages/real-estate/offices
JS blob
