### ISSUE TITLE
Allegro One Punkt vs Allegro One Box (some claimed amenity=parcel_locker are merely post_office=post_partner)

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#8728]
the same as #8717 #8716 

"Allegro One Punkt" -> post_office=post_partner

"Allegro One Box" ->  amenity=parcel_locker

https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/allegro_one_box.py

(also, when I tried URL stated there - it failed, maybe this spider got broken? Or I failed at copy-pasting?)

**Comment by ireun** [comment]
For some reason I cannot run this spider:

```
ubuntu@67c0ebdba7d0:/workspaces/alltheplaces$ pipenv run scrapy crawl allegro_one_box
2024-06-30 11:31:01 [scrapy.utils.log] INFO: Scrapy 2.11.2 started (bot: locations)
2024-06-30 11:31:01 [scrapy.utils.log] INFO: Versions: lxml 5.2.2.0, libxml2 2.12.6, cssselect 1.2.0, parsel 1.9.1, w3lib 2.1.2, Twisted 24.3.0, Python 3.11.9 (main, Jun 30 2024, 11:08:53) [GCC 11.4.0], pyOpenSSL 24.1.0 (OpenSSL 3.2.1 30 Jan 2024), cryptography 42.0.7, Platform Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/alltheplaces-7i_IfSds/lib/python3.11/site-packages/scrapy/spiderloader.py", line 87, in load
    return self._spiders[spider_name]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'allegro_one_box'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/alltheplaces-7i_IfSds/bin/scrapy", line 8, in <module>
    sys.exit(execute())
             ^^^^^^^^^
  File "/home/ubuntu/.local/share/virtualenvs/alltheplaces-7i_IfSds/lib/python3.11/site-packages/scrapy/cmdline.py", line 161, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/home/ubuntu/.local/share/virtualenvs/alltheplaces-7i_IfSds/lib/python3.11/site-packages/scrapy/cmdline.py", line 114, in _run_print_help
    func(*a, **kw)
  File "/home/ubuntu/.local/share/virtualenvs/alltheplaces-7i_IfSds/lib/python3.11/site-packages/scrapy/cmdline.py", line 169, in _run_command
    cmd.run(args, opts)
  File "/home/ubuntu/.local/share/virtualenvs/alltheplaces-7i_IfSds/lib/python3.11/site-packages/scrapy/commands/crawl.py", line 23, in run
    crawl_defer = self.crawler_process.crawl(spname, **opts.spargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/virtualenvs/alltheplaces-7i_IfSds/lib/python3.11/site-packages/scrapy/crawler.py", line 264, in crawl
    crawler = self.create_crawler(crawler_or_spidercls)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/virtualenvs/alltheplaces-7i_IfSds/lib/python3.11/site-packages/scrapy/crawler.py", line 300, in create_crawler
    return self._create_crawler(crawler_or_spidercls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/virtualenvs/alltheplaces-7i_IfSds/lib/python3.11/site-packages/scrapy/crawler.py", line 385, in _create_crawler
    spidercls = self.spider_loader.load(spidercls)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/virtualenvs/alltheplaces-7i_IfSds/lib/python3.11/site-packages/scrapy/spiderloader.py", line 89, in load
    raise KeyError(f"Spider not found: {spider_name}")
KeyError: 'Spider not found: allegro_one_box'
```

**Comment by matkoniecz** [comment]
note `    name = "allegro_one_box_pl"`


have you tried running `allegro_one_box_pl` ?

**Comment by ireun** [comment]
Thanks! Can you show show me ref number of that "Allegro One Punkt" I can't see any wrong result with this crawler..

**Comment by matkoniecz** [comment]
sorry! This one is fine after all! (I tried running spider locally but it kept refusing to fetch the page with data, now I checked published ATP data and it looks like it is filtered already)

sorry for a false alarm
