### ISSUE TITLE
Taco Johns results in exception

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#9647]
### Spider name

taco_johns_us

### Log output

https://alltheplaces-data.openaddresses.io/runs/2024-07-06-13-31-59/logs/taco_johns_us.txt

### Backtrace (if applicable)
```
2024-07-07 12:23:32 [scrapy.core.scraper] ERROR: Spider error processing <GET https://locations.tacojohns.com/index/> (referer: None)
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/utils/defer.py", line 279, in iter_errback
    yield next(it)
          ^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/utils/python.py", line 350, in __next__
    return next(self.data)
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/utils/python.py", line 350, in __next__
    return next(self.data)
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/core/spidermw.py", line 106, in process_sync
    for r in iterable:
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/spidermiddlewares/referer.py", line 352, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/core/spidermw.py", line 106, in process_sync
    for r in iterable:
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/spidermiddlewares/urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/core/spidermw.py", line 106, in process_sync
    for r in iterable:
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/spidermiddlewares/depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/core/spidermw.py", line 106, in process_sync
    for r in iterable:
  File "/home/ubuntu/locations/spiders/taco_johns_us.py", line 22, in parse
    for location in response.json()["objects"]:
                    ^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/site-packages/scrapy/http/response/text.py", line 85, in json
    self._cached_decoded_json = json.loads(self.body)
                                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by CloCkWeRX** [comment]
Works manually

**Comment by CloCkWeRX** [comment]
And magically started working again.
