### ISSUE TITLE
Miller's Ale House

### ISSUE THREAD

**Issue by wessport** [alltheplaces/alltheplaces#996]
https://millersalehouse.com/locations/

**Comment by CloCkWeRX** [comment]
```
import chompjs
from scrapy import Selector

from locations.json_blob_spider import JSONBlobSpider


class MillersAleHouseUSSpider(JSONBlobSpider):
    name = "millers_ale_house_us"
    item_attributes = {
        "brand": "Millers Ale House",
        "brand_wikidata": "Q6858987",
    }
    allowed_domains = ["millersalehouse.com"]
    start_urls = ["https://millersalehouse.com/locations/"]

    def extract_json(self, response):
        data = response.xpath("//script[contains(text(), 'var locations = ')]/text()").get().replace("new google.maps.LatLng", "")
        return chompjs.parse_js_object(data)

```
However

```
2024-08-18 07:21:48 [scrapy.core.scraper] ERROR: Spider error processing <GET https://millersalehouse.com/locations/> (referer: None)
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/alltheplaces-7i_IfSds/lib/python3.11/site-packages/scrapy/utils/defer.py", line 279, in iter_errback
    yield next(it)
          ^^^^^^^^
  File "/home/ubuntu/.local/share/virtualenvs/alltheplaces-7i_IfSds/lib/python3.11/site-packages/scrapy/utils/python.py", line 350, in __next__
    return next(self.data)
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/virtualenvs/alltheplaces-7i_IfSds/lib/python3.11/site-packages/scrapy/utils/python.py", line 350, in __next__
    return next(self.data)
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/virtualenvs/alltheplaces-7i_IfSds/lib/python3.11/site-packages/scrapy/core/spidermw.py", line 106, in process_sync
    for r in iterable:
  File "/workspaces/alltheplaces/locations/middlewares/track_sources.py", line 31, in process_spider_output
    for item in result or []:
  File "/home/ubuntu/.local/share/virtualenvs/alltheplaces-7i_IfSds/lib/python3.11/site-packages/scrapy/core/spidermw.py", line 106, in process_sync
    for r in iterable:
  File "/home/ubuntu/.local/share/virtualenvs/alltheplaces-7i_IfSds/lib/python3.11/site-packages/scrapy/spidermiddlewares/referer.py", line 352, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/virtualenvs/alltheplaces-7i_IfSds/lib/python3.11/site-packages/scrapy/core/spidermw.py", line 106, in process_sync
    for r in iterable:
  File "/home/ubuntu/.local/share/virtualenvs/alltheplaces-7i_IfSds/lib/python3.11/site-packages/scrapy/spidermiddlewares/urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/virtualenvs/alltheplaces-7i_IfSds/lib/python3.11/site-packages/scrapy/core/spidermw.py", line 106, in process_sync
    for r in iterable:
  File "/home/ubuntu/.local/share/virtualenvs/alltheplaces-7i_IfSds/lib/python3.11/site-packages/scrapy/spidermiddlewares/depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/virtualenvs/alltheplaces-7i_IfSds/lib/python3.11/site-packages/scrapy/core/spidermw.py", line 106, in process_sync
    for r in iterable:
  File "/workspaces/alltheplaces/locations/json_blob_spider.py", line 30, in parse
    locations = self.extract_json(response)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/alltheplaces/locations/spiders/millers_ale_house_us.py", line 19, in extract_json
    return chompjs.parse_js_object(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/virtualenvs/alltheplaces-7i_IfSds/lib/python3.11/site-packages/chompjs/chompjs.py", line 74, in parse_js_object
    return json.loads(parsed_data, **json_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.9/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid control character at: line 1 column 3355 (char 3354)
2024-08-18 07:21:48 [scrapy.core.engine] INFO: Closing spider (finished)
2024-08-18 07:21:48 [locations.pipelines.duplicates] INFO: Dropped 0 duplicate items
2024-08-18 07:21:48 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'atp/cdn/cloudflare/response_count': 2,
 'atp/cdn/cloudflare/response_status_count/200': 2,
 'downloader/request_bytes': 620,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 146264,
 'downloader/response_count': 2,
 'downloader/response_status_count/200': 2,
 'elapsed_time_seconds': 1.818749,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2024, 8, 18, 7, 21, 48, 977601, tzinfo=datetime.timezone.utc),
 'httpcompression/response_bytes': 729467,
 'httpcompression/response_count': 2,
 'log_count/DEBUG': 3,
 'log_count/ERROR': 1,
 'log_count/INFO': 9,
 'memusage/max': 176082944,
 'memusage/startup': 176082944,
 'response_received_count': 2,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/200': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'spider_exceptions/JSONDecodeError': 1,
 'start_time': datetime.datetime(2024, 8, 18, 7, 21, 47, 158852, tzinfo=d
```
